const PrivacyPolicy = () => {
  return (
    <section className="py-12">
      <div className="container mx-auto">
        <h2 className="text-3xl font-bold mb-6">Privacy Policy</h2>

        <p className="mb-4">
          Your privacy is important to us. It is our policy to respect your privacy regarding any information we may
          collect from you across our website, and other sites we own and operate.
        </p>

        <p className="mb-4">
          We only ask for personal information when we truly need it to provide a service to you. We collect it by fair
          and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it
          will be used.
        </p>

        <p className="mb-4">
          We only retain collected information for as long as necessary to provide you with your requested service. What
          data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as
          unauthorized access, disclosure, copying, use or modification.
        </p>

        <p className="mb-4">
          We don’t share any personally identifying information publicly or with third-parties, except when required to
          by law.
        </p>

        <p className="mb-4">
          You are free to refuse our request for your personal information, with the understanding that we may be unable
          to provide you with some of your desired services.
        </p>

        <p className="mb-4">
          Your continued use of our website will be regarded as acceptance of our practices around privacy and personal
          information. If you have any questions about how we handle user data and personal information, feel free to
          contact us.
        </p>

        <h3 className="text-2xl font-semibold mt-8 mb-4">This policy is effective as of [Date].</h3>

        <p>
          Generated by{" "}
          <a
            href="https://www.websitepolicies.com/blog/privacy-policy-template"
            target="_blank"
            rel="noopener noreferrer"
          >
            WebsitePolicies.com Privacy Policy Generator
          </a>
        </p>
      </div>
    </section>
  )
}

export default PrivacyPolicy
